### ISSUE TITLE
View dashboard

### ISSUE THREAD

**Issue by R1N4-Devo** [Devoteam/ConnectivityServiceDevelopment#11]
**As a** logged-in user, 
**I want to** view the dashboard of my Skoda Connect Services car app, 
**so that** I can see an overview of my account and activities.

### **Acceptance Criteria:**

1. **Dashboard Display**:
   - The user should be able to navigate to all of the Services that are available in ther Skoda Connect Shop which is accessible via https://shop.skoda-connect.com/
   -  All the services are displayed in a tile and contain a picture, a title, a short info text and a subscribe-button

2. **User Interface:**
   - The app should have a user-friendly interface optimized for in-car use based on the Skoda Connect Shop which is accessible via https://shop.skoda-connect.com/
   - Buttons and controls should be large and easy to interact with
   - The dashboard should be responsive and displayed correctly on different screen sizes
   - All elements that are used are based on the Skoda Flow Design System: https://flow.skoda-brand.com/

### **Skribbles**

Car app (navigation menu is optional)
![Image](https://github.com/user-attachments/assets/c78d71b3-3e67-4306-a55b-5f4a4e47213c)

Mobile app
![Image](https://github.com/user-attachments/assets/ec696e38-f807-48e9-8edc-f32987ca89d3)

**Comment by Smootje** [comment]
Closed with PR #32
