### ISSUE TITLE
Implement Driver Distraction Rule

### ISSUE THREAD

**Issue by R1N4-Devo** [Devoteam/ConnectivityServiceDevelopment#13]
**As a** developer, 
**I want to** implement a distraction rule in the in-car app, 
**so that** the driver cannot use the app while the car is moving.

**Acceptance Criteria:**

1. **Driving State Detection**:

   - The app should detect when the car is moving.

2. **Distraction Rule Activation**:

   - When the car is moving, the app should disable all interactive features for the driver.
   - The app should display a message indicating that the app is disabled while driving.

**Comment by Smootje** [comment]
Closed by PR #35
