### ISSUE TITLE
Test image storage and retrieval with MySQL

### ISSUE THREAD

**Issue by VSCHNE** [Devoteam/ConnectivityServiceDevelopment#17]
This ticket focuses on testing the functionality of storing and retrieving images within the application's MySQL database. We will verify that images can be successfully uploaded manually to the database and then retrieved via the `/products/image` endpoint.

**Tasks:**

*   Modify the existing product entity to include a field for storing image data (e.g., as a BLOB or VARCHAR to store the image path/URL).
*   Update the repository interface to include methods for retrieving product entities with image data.
*   Develop comprehensive tests to cover the following scenarios:
    *   Successfully saving a product with an image to the database with database means.
    *   Retrieving a product with an image from the database.

**Acceptance Criteria:**

*   The application should be able to retrieve stored image data within the MySQL database.
*   The `/products/image` endpoint should correctly retrieve and return image data for a given product ID.

**Comment by VSCHNE** [comment]
Images can be inserted by an INSERT statement like this:

insert into csd.product (id,category,name,description,image)
values
(2,'Cars','Scala','This is also a good car',LOAD_FILE('c:\Skoda\Ausschreibung\Bilder\Default_bp1200_1.webp'));

**Comment by VSCHNE** [comment]
[CSD.postman_collection.json](https://github.com/user-attachments/files/17487586/CSD.postman_collection.json)

**Comment by pgerke** [comment]
That would fulfill the acceptance criteria, right @VSCHNE ?

**Comment by VSCHNE** [comment]
Yes!

**Comment by VSCHNE** [comment]
Images can be stored by uploading them by a database tool. The images are returned by calling /products/image/{id} end point.

**Comment by VSCHNE** [comment]
Backend JUnit tests completed.
