### ISSUE TITLE
Subscribe to a Service

### ISSUE THREAD

**Issue by R1N4-Devo** [Devoteam/ConnectivityServiceDevelopment#18]
**As a** logged-in user,
**I want to** subscribe to different Skoda Connect Services,
**so that** I can access advanced features and services for my vehicle.

**Acceptance Criteria**

1. **Subscription Process**:
   - Users can select multiple Connect Services to subscribe to.
   - The process is straightforward and intuitive.
   - It is not possible for a user to unsubscribe a service.

2. **Service Activation**:
   - Connect Services are activated immediately upon successful subscription.

3. **Account Management**:
   - Users can view and manage their subscriptions from their account settings.

4. **Error Handling**:
   - Users receive clear error messages if there are issues during the subscription process.
   - Failed transactions or other errors are logged for troubleshooting.

5. **Security**:
   - User data related to subscriptions is securely stored and encrypted.

**Comment by Smootje** [comment]
Closed by PR #33
