### ISSUE TITLE
Test Data for Validation

### ISSUE THREAD

**Issue by R1N4-Devo** [Devoteam/ConnectivityServiceDevelopment#22]
**As a** developer, 
**I want to** generate and save test data in the database 
**so that** I can verify that the application performs correctly with various data inputs and scenarios.

**Acceptance Criteria**

1. **Test Data Generation**:
   - Create a script or use a tool to generate realistic test data covering different use cases.

2. **Database Schema**:
   - Verify that the database schema is correctly defined and supports the required data types.

3. **Data Insertion**:
   - Develop a process to insert the generated test data into the database.

4. **Data Validation**:
   - Validate the inserted data to ensure it matches the expected format and values.

5. **Documentation**:
   - Document the process for generating, inserting, and validating test data.

**Comment by VSCHNE** [comment]
Insert script for testing data attached:
[insert-test-data.txt](https://github.com/user-attachments/files/17493391/insert-test-data.txt)

**Comment by VSCHNE** [comment]
Test data was created in all the databases and is correctly returned.
