### ISSUE TITLE
Set up Monitoring

### ISSUE THREAD

**Issue by R1N4-Devo** [Devoteam/ConnectivityServiceDevelopment#23]
**As a** developer, 
**I want to** set up monitoring using AWS CloudWatch
**so that** I can track and debug application performance and health.

**Acceptance Criteria**

1. **CloudWatch Setup**:
   - Configure AWS CloudWatch to collect and store logs from all application instances.
   - Set up CloudWatch metrics to monitor system performance (CPU, memory, disk I/O, etc.).

2. **Error Handling**:
   - Ensure logs and traces include error messages and stack traces for debugging.
   - Implement retention policies for log data to manage storage costs.

3. **Security**:
   - Ensure CloudWatch logs are encrypted at rest and in transit.
   - Set up IAM roles and permissions to restrict access to monitoring data.

**Comment by pgerke** [comment]
All application logs are shipped to Cloudwatch logs. The application load balancerk, ECS Cluster, Service and tasks as well as the Aurora Database are reporting metrices to Cloudwatch Metrics. Anomaly detection is enabled as well as AI enhanced recommendations based on AWS DevOps Guru. A notification service based on SNS is set up and will send notifications and alerts via email.
