### ISSUE TITLE
AWS Account Creation and Initial User Setup

### ISSUE THREAD

**Issue by pgerke** [Devoteam/ConnectivityServiceDevelopment#3]
**As an** IT administrator,  
**I want to** create and configure a new AWS account with secure user access,  
**so that** both an "admin" and a restricted "user" can manage the AWS resources securely with MFA enabled.

#### Acceptance Criteria:
1. **AWS Account Setup:**
   - A new AWS account is created with proper billing and organization information.

2. **Admin User Creation:**
   - An IAM user named "admin" is created with full administrative access.
   - MFA is enabled for the "admin" user to enforce two-factor authentication.

3. **Restricted User Creation:**
   - An IAM user named "user" is created with restricted permissions, allowing access to specific AWS services (e.g., read-only access to CloudWatch, ECS, and API Gateway).
   - MFA is enabled for the "user" to enforce two-factor authentication.

4. **Initial Security Configuration:**
   - A strong password policy is enforced for the AWS account (e.g., requiring special characters and a minimum length).
   - MFA is enforced for both users (admin and user).

5. **Access Keys:**
   - Access keys for "admin" and "user" are generated and securely stored in a password manager.

**Comment by R1N4-Devo** [comment]
Done, user "admin" has administrator access, user "user" has read-only access. 
Both are stored in 1Password and can by access by all team members.
