### ISSUE TITLE
Implement AI in AWS cloud Services

### ISSUE THREAD

**Issue by R1N4-Devo** [Devoteam/ConnectivityServiceDevelopment#31]
**As a** DevOps engineer, 
**I want to** implement AI-enhanced recommendations using AWS DevOps Guru 
**so that I** can proactively identify and resolve issues in my cloud infrastructure.

### **Acceptance Criteria**

**1. Service Integration:**
  - Enable AWS DevOps Guru on the necessary AWS accounts and resources.
  - Ensure all critical components (e.g., ECS instances, RDS databases) are monitored by DevOps Guru.

**2. Data Collection:**
   - Collect metrics, logs, and traces from the monitored resources.
   - Ensure that data is consistently and accurately gathered for analysis.

**3. AI Analysis:**
   - Use DevOps Guru to analyze collected data and identify anomalies.
   - Ensure the AI model is configured to provide insights and recommendations based on detected anomalies.

**4. Recommendation Implementation:**
   - Display AI-generated recommendations in a user-friendly dashboard.
   - Categorize recommendations by priority and potential impact. 
   - Ensure recommendations are actionable, with clear steps for resolution.

**5. Alerting and Notifications:**
   - Set up notifications to alert the DevOps team of critical recommendations.
   - Ensure alerts are sent via preferred communication channels (e.g., email).

**6. Security and Compliance:**
   - Ensure that data collected by DevOps Guru is encrypted and complies with relevant security standards.
   - Implement access controls to restrict who can view and act on AI recommendations.

**Comment by pgerke** [comment]
Done. All logs, traces, metrics and insights are ingested into DevOps Guru. I have created an SNS topic that will notify me incase of recommendations. I will also be alerted via the same SNS topic in case of alerts, for example if a serverless ressource (e.g. Aurora, ECS) exceeds their scaling limit. On the cloudwatch side, AI assisted anomaly detection is enabled for all relevant Cloudwatch log streams. See: https://eu-central-1.console.aws.amazon.com/devops-guru/dashboard?insight-type=reactive&region=eu-central-1
